services:
  - type: web
    name: aquatour-crm
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: aquatour-db
          property: connectionString

databases:
  - name: aquatour-db
    databaseName: aquatour
    user: aquatour_user
    plan: free
